# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc0225084444d671c689eb5e863cc2e416bbe769deeeae540b92404a7f9bc1d1d04666fec112fedf33bbfd99da4ad3bb43030a61301965860f33aa06f889f76

test:
  secret_key_base: 3f35a119ed9999256a2a7117c76dcb9869e59dbb9e9198356048f4559f4bdaa864c5f9dbbf2205a4a169888d01c4dfd114862acc82d06e6d2bef9ead3125af96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
